nats:
  url: "nats://localhost:4222" # Sẽ bị override bởi RUNNER_NATS_URL
  submissionCreatedSubject: "submission.jobs"
  submissionResultSubject: "submission.results"
  queueGroup: "coderunner_prod_group"

runner:
  sandboxBaseDir: "C:/Users/BaoBao/Downloads/tem" # Sẽ bị override bởi RUNNER_RUNNER_SANDBOXBASEDIR
  compilationTimeoutSec: 45
  maxConcurrentJobs: 20
