nats:
  url: "nats://localhost:4222" # Sẽ bị override bởi RUNNER_NATS_URL
  submissionCreatedSubject: "submission.created"
  submissionResultSubject: "submission.executed"
  queueGroup: "coderunner_prod_group"

runner:
  sandboxBaseDir: "./temp" # Sẽ bị override bởi RUNNER_RUNNER_SANDBOXBASEDIR
  compilationTimeoutSec: 45
  maxConcurrentJobs: 20
